config/routes.rb
CheckIt::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "users#new"

  resources :users
  resources :sessions
  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :sender, :class_name => "User", :foreign_key => :sender_id
  belongs_to :recipient, :class_name => "User", :foreign_key => :recipient_id

  attr_accessible :url, :sender, :recipient

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  validates_presence_of :first_name
  validates_presence_of :last_name

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    logger.info(session[:user_id])
    return @current_user
  end

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in"
      redirect_to :root
      return false
    else
      logger.info(@current_user)
      return true 
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :confirm_logged_in

  include Embed

  def index
    @links = Link.where(recipient_id: current_user.id)
  end

  def create
    @link = Link.new
    @link.sender = current_user
    @link.recipient = User.find(params[:recipient_id])
    @link.url = params[:url]
    @link.save
    redirect_to :action => 'index'
    flash[:notice] = "Success!"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to :controller => 'links', :action => 'index'
    else
      redirect_to root_url, :alert => "invalid login"
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :authenticity_token))
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <%= render "shared/menu" %>
<body>

  <div >
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/links/index.html.erb
<%- model_class = Link -%>
<div id="container" class="js-masonry"
    data-masonry-options='{ "columnWidth": 200, "itemSelector": ".item" }'>
  <div id="columns">
  <% @links.each do |link| %>
    <% embed = Embed.get_embed(link.url) %>
    <% puts embed %>
    <div class="pin">
      <img src=<%= embed.thumbnail_url %>>
      <p>
      <a href=<%= embed.url %>> <%= embed.title %> </a>
      </p>
      <span>from <%= link.sender.first_name  %></span>
      <span>via <%= embed.provider_name %></span>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_menu.html.erb
<%= nav_bar :fixed => :top, :brand => "Check It!" do %>
  <% if current_user %>
    <%= menu_group :pull => :right do %>
      <%= menu_item "Log Out", log_out_path %>
    <% end %>
    <%= menu_group :pull => :right do %>
      <%= form_tag links_path, :class => "form-inline" do %>
        <%= select_tag(:recipient_id, options_from_collection_for_select(User.all, "id", "email")) %>
        <%= text_field_tag :url, params[:url], placeholder: "url" %>
        <%= submit_tag "Send", class: "btn btn-success"%>
      <% end %>
    <% end %>
  <% else %>
    <%= menu_group :pull => :right do %>
      <%= form_tag sessions_path, :class => "form-inline" do %>
        <%= text_field_tag :email, params[:email], placeholder: "email" %>
        <%= password_field_tag :password, params[:password], placeholder: "password" %>
        <%= submit_tag "Log In", class: "btn btn-success"%>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
<h1> Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :first_name, placeholder: "First Name" %> <br/>
    <%= f.text_field :last_name, placeholder: "Last Name"  %> <br/>
    <%= f.text_field :email, placeholder: "Email" %> <br/>
    <%= f.password_field :password, placeholder: "Password" %> <br/>
    <%= f.password_field :password_confirmation, placeholder: "Re-enter Password" %> <br/>

    <p class="button"><%= f.submit "Register" %></p>

<% end %>
</div>